import { Option } from '../../parts/select/select';

export const SWISS_CANTONS: Option[] = [
  { value: 1, label: 'Aargau' },
  { value: 2, label: 'Appenzell Innerrhoden' },
  { value: 3, label: 'Appenzell Ausserrhoden' },
  { value: 4, label: 'Bern' },
  { value: 5, label: 'Basel-Landschaft' },
  { value: 6, label: 'Basel-Stadt' },
  { value: 7, label: 'Freiburg' },
  { value: 8, label: 'Genf' },
  { value: 9, label: 'Glarus' },
  { value: 10, label: 'Graubünden' },
  { value: 11, label: 'Jura' },
  { value: 12, label: 'Luzern' },
  { value: 13, label: 'Neuenburg' },
  { value: 14, label: 'Nidwalden' },
  { value: 15, label: 'Obwalden' },
  { value: 16, label: 'St. Gallen' },
  { value: 17, label: 'Schaffhausen' },
  { value: 18, label: 'Solothurn' },
  { value: 19, label: 'Schwyz' },
  { value: 20, label: 'Thurgau' },
  { value: 21, label: 'Tessin' },
  { value: 22, label: 'Uri' },
  { value: 23, label: 'Waadt' },
  { value: 24, label: 'Wallis' },
  { value: 25, label: 'Zug' },
  { value: 26, label: 'Zürich' },
];
